# Assignment 4: clustering and classification 

```{r}
#installing libraries
library(tidyr)
library (MASS)
library(corrplot)
library(ggplot2)
```

```{r}
# loading the data
data("Boston")

# exploring the dataset

str(Boston)
summary(Boston)

pairs(Boston)

```

## Description here


```{r}
#visual examination
pairs(Boston)

cor_matrix <- cor(Boston) 

cor_matrix %>%
  round(2)

corrplot(cor_matrix, method="circle",)

corrplot(cor_matrix, method="circle", type ="upper",cl.pos = "b", tl.pos = "d", tl.cex = 0.6)

```


## Description here
 
### 4
```{r}
# center and standardize variables
boston_scaled <- scale(Boston)

summary((boston_scaled))

boston_scaled <- as.data.frame(boston_scaled)

#the new variable
bins <- quantile(boston_scaled$crim)
bins

# create a categorical variable 'crime'
v<- c("low", "med_low", "med_high", "high")
crime <- cut(boston_scaled$crim, breaks = bins, include.lowest = TRUE, label=v)

table(crime)

# remove original crim from the dataset
boston_scaled <- dplyr::select(boston_scaled, -crim)

# add the new categorical value to scaled data
boston_scaled <- data.frame(boston_scaled, crime)

#divide the dataset

n <- nrow(boston_scaled)

# choose randomly 80% of the rows
ind <- sample(n,  size = n * 0.8)

# create train set
train <- boston_scaled[ind,]

# create test set 
test <- boston_scaled[-ind,]

# save the correct classes from test data
correct_classes <- test$crime

# remove the crime variable from test data
test <- dplyr::select(test, -crime)

```


## 5 LDA
```{r}
# linear discriminant analysis
lda.fit <- lda(crime ~ ., data = train)

# print the lda.fit object
lda.fit

# the function for lda biplot arrows
lda.arrows <- function(x, myscale = 1, arrow_heads = 0.1, color = "red", tex = 0.75, choices = c(1,2)){
  heads <- coef(x)
  arrows(x0 = 0, y0 = 0, 
         x1 = myscale * heads[,choices[1]], 
         y1 = myscale * heads[,choices[2]], col=color, length = arrow_heads)
  text(myscale * heads[,choices], labels = row.names(heads), 
       cex = tex, col=color, pos=3)
}

# target classes as numeric
classes <- as.numeric(train$crime)

# plot the lda results
plot(lda.fit, dimen = 2, col = classes, pch = classes)
lda.arrows(lda.fit, myscale = 2)

```

#6

```{r}
# predict classes with test data
lda.pred <- predict(lda.fit, newdata = test)

# cross tabulate the results
table(correct = correct_classes, predicted = lda.pred$class)

```

#7

```{r}
data("Boston")
Boston <- scale(Boston)
#summary(Boston)


# euclidean distance matrix
dist_eu <- dist(Boston)

# look at the summary of the distances
summary(dist_eu)

# manhattan distance matrix
dist_man <- dist(Boston, method="manhattan")

# look at the summary of the distances
#summary(dist_eu)
summary(dist_man)



#k-means

# k-means clustering
set.seed(13)
km <- kmeans(Boston, centers =3)

#km$cluster

# plot the Boston dataset with clusters
pairs(Boston, col = km$cluster )

pairs(Boston [6:10], col = km$cluster )



set.seed(123)

# determine the number of clusters
k_max <- 10

# calculate the total within sum of squares
twcss <- sapply(1:k_max, function(k){kmeans(Boston, k)$tot.withinss})

# visualize the results
qplot(x = 1:k_max, y = twcss, geom = 'line')

# k-means clustering
km <- kmeans(Boston, centers = 2)

# plot the Boston dataset with clusters
pairs(Boston, col = km$cluster)





```


